### ISSUE TITLE
OAuth2 Principal 캐스팅 문제

### ISSUE THREAD

**Issue by ybell1028** [YAPP-18th/Web-Team-1-Backend#21]
OAuth2AuthenticationSuccessHandler -> determineTargetUrl -> createRefreshToken에서

`authentication.getPrincipal();`을 `UserDetails` 상속받은 `UserPrincipal` 클래스로 캐스팅하려고 했으나

```
java.lang.ClassCastException: org.springframework.security.oauth2.core.user.DefaultOAuth2User cannot be cast to com.yapp18.retrospect.security.UserPrincipal
	at com.yapp18.retrospect.service.TokenService.createRefreshToken(TokenService.java:46) ~[main/:na]
	at com.yapp18.retrospect.security.oauth2.OAuth2AuthenticationSuccessHandler.determineTargetUrl(OAuth2AuthenticationSuccessHandler.java:62) ~[main/:na]
	at com.yapp18.retrospect.security.oauth2.OAuth2AuthenticationSuccessHandler.onAuthenticationSuccess(OAuth2AuthenticationSuccessHandler.java:41) ~[main/:na]
```

에러로 불가. 직접 UserDetails로도 시도해봤으나 안됨. 

expression보면 principal 종류가 여러개라 authentication을 지정해줘야 하는 것 같은데 아직 방법을 모르겠음...

**Comment by ybell1028** [comment]
`String accessToken = TokenService.createAccessToken((DefaultOAuth2User) authentication.getPrincipal());`

DefaultOAuth2User로 캐스팅해서 해결
